# Font
FONT_FAMILY = "Mona12"

FONT_SIZE_BASE = 18
FONT_SIZE_HEADER = 40

# Color
COLOR_BACKGROUND = "#343D3F"
COLOR_TEXT = "#F6F6F6"
COLOR_SELECTED_BACKGROUND = "#B8CACD"
COLOR_SELECTED_TEXT = "#343D3F"

# 같은 색을 Border에도 사용
COLOR_BORDER = COLOR_SELECTED_BACKGROUND

# Spacing
SPACE_12 = 12
SPACE_16 = 16
SPACE_24 = 24
SPACE_32 = 32

# Border
BORDER_RADIUS = 10

# Grid
GRID_PC_MAX_WIDTH = 1280
GRID_TABLET_MAX_WIDTH = 768
GRID_MOBILE_MAX_WIDTH = 390

GRID_PC_COLUMNS = 12
GRID_TABLET_COLUMNS = 8
GRID_MOBILE_COLUMNS = 4