FONT_FAMILY = "Mona12"

FONT_SIZE_TABLE = 12
FONT_SIZE_SMALL = 14
FONT_SIZE_BASE = 18
FONT_SIZE_HEADER = 40

COLOR_BACKGROUND = "#343D3F"
COLOR_TEXT = "#F6F6F6"
COLOR_SELECTED = "#B8CACD"
COLOR_SELECTED_TEXT = COLOR_BACKGROUND

SPACE_8 = 8
SPACE_12 = 12
SPACE_16 = 16
SPACE_24 = 24
SPACE_32 = 32

BORDER_RADIUS = 10

SCROLLBAR_SIZE = 6
SCROLLBAR_RADIUS = 3

GRID_PC_MAX_WIDTH = 1280
GRID_TABLET_MAX_WIDTH = 768
GRID_MOBILE_MAX_WIDTH = 390

GRID_PC_COLUMNS = 12
GRID_TABLET_COLUMNS = 8
GRID_MOBILE_COLUMNS = 4

WINDOW_HEIGHT = 760

# Data Preview에서 한 번에 표시할 Row와 Column 수
PREVIEW_ROW_COUNT = 10
PREVIEW_COLUMN_COUNT = 5

# Column 이름과 dtype을 여러 줄로 표시할 Header 높이
TABLE_HEADER_HEIGHT = 92