FONT_FAMILY = "Noto Sans KR"

FONT_SIZE_TABLE = 8
FONT_SIZE_SMALL = 10
FONT_SIZE_BASE = 12
FONT_SIZE_SECTION = 14
FONT_SIZE_LARGE = 18
FONT_SIZE_HEADER = 26

# Color
COLOR_PRIMARY = "#ACACDE"
COLOR_SECONDARY = "#C490D1"
COLOR_OFF_WHITE = "#F6F6F6"
COLOR_OFF_BLACK = "#353535"

# Space
SPACE_XS = 8
SPACE_SM = 16
SPACE_MD = 24
SPACE_LG = 32
SPACE_XL = 48
SPACE_2XL = 64

# PC Layout
GRID_PC_MAX_WIDTH = 1280
GRID_PC_PADDING_X = SPACE_LG
GRID_PC_PADDING_Y = SPACE_XL
GRID_PC_COLUMNS = 12
GRID_PC_GUTTER = SPACE_MD

# Radius
RADIUS_SM = 8
RADIUS_MD = 16

# Scrollbar
SCROLLBAR_SIZE = 8
SCROLLBAR_RADIUS = 4

# Home
HOME_CARD_WIDTH = 252
HOME_CARD_HEIGHT = 204

WINDOW_HEIGHT = 760

# Data Preview
PREVIEW_ROW_COUNT = 10
PREVIEW_COLUMN_COUNT = 5
TABLE_HEADER_HEIGHT = 92